---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  # - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: check-added-large-files
  - id: requirements-txt-fixer
  - id: check-executables-have-shebangs
  # no-commit-to-branch
# - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
#   rev: 0.2.2     # or other specific tag
#   hooks:
#   - id: yamlfmt
#     args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

- repo: https://github.com/ansible/ansible-lint.git
  rev: v6.4.0
  hooks:
  - id: ansible-lint
    files: \.(yaml|yml)$
