---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - ack
  - adns
  - ansible
  - ansible-lint
  - ant
  - antigen
  - aom
  - apr
  - apr-util
  - argo
  - argon2
  - arp-scan
  - asciinema
  - aspcud
  - aspell
  - assimp
  - atk
  - atkmm
  - atkmm@2.28
  - autoconf
  - autojump
  - automake
  - avro-c
  - aws-elasticbeanstalk
  - aws-iam-authenticator
  - aws-sam-cli
  - awscli
  - bash
  - bash-completion
  - bdw-gc
  - berkeley-db
  - binutils
  - bison
  - boost
  - boost-build
  - bosh-cli
  - brotli
  - c-ares
  - ca-certificates
  - cabal-install
  - cabextract
  - cairo
  - cairomm
  - cairomm@1.14
  - cask
  - ccache
  - ccat
  - cf-cli
  - cfssl
  - checkstyle
  - chezscheme
  - cjson
  - clingo
  - clisp
  - clojure
  - cloog
  - cloog018
  - cmake
  - cmatrix
  - cmocka
  - coreutils
  - cowsay
  - cscope
  - cunit
  - curl
  - curl-openssl
  - dav1d
  - dbus
  - deno
  - diffutils
  - direnv
  - ditaa
  - docbook
  - docbook-xsl
  - docker
  - dockutil
  - dos2unix
  - double-conversion
  - dovecot
  - doxygen
  - ed
  - eksctl
  - elinks
  - emacs
  - emacs-plus@28
  - exa
  - exercism
  - faac
  - fasd
  - fd
  - fdk-aac
  - ffmpeg
  - figlet
  - findutils
  - fish
  - flac
  - fmt
  - folly
  - fontconfig
  - fortune
  - freetds
  - freetype
  - frei0r
  - fribidi
  - fswatch
  - fzf
  - gawk
  - gcc
  - gd
  - gdb
  - gdbm
  - gdk-pixbuf
  - gettext
  - gflags
  - ghc
  - ghostscript
  - giflib
  - gifsicle
  - git
  - git-flow
  - git-lfs
  - github/gh/gh
  - glances
  - glib
  - glib-networking
  - glibmm
  - glibmm@2.64
  - glibmm@2.66
  - glog
  - gmime
  - gmp
  - gnu-getopt
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnu-which
  - gnupg
  - gnupg2
  - gnutls
  - go
  - gobject-introspection
  - goreleaser
  - gox
  - gpatch
  - gpg
  - gpgme
  - graphite2
  - graphviz
  - grep
  - grok
  - groovy
  - gsettings-desktop-schemas
  - gsl
  - gtk+
  - gtk+3
  - gtkmm
  - gts
  - guile
  - gzip
  - hadolint
  - haproxy
  - harfbuzz
  - helm
  - hh
  - hicolor-icon-theme
  - highlight
  - hiredis
  - hstr
  - htop
  - httpd
  - httpie
  - httrack
  - hub
  - hunspell
  - hydra
  - icu4c
  - imagemagick
  - imagemagick@6
  - imath
  - imlib2
  - intltool
  - iperf
  - isl
  - isl@0.18
  - ispell
  - isync
  - itstool
  - jansson
  - jasper
  - jbig2dec
  - jemalloc
  - jhipster
  - jmeter
  - jpeg
  - jpeg-xl
  - jq
  - jx
  - kcat
  - kompose
  - kotlin
  - krb5
  - kube-ps1
  - kubectx
  - kubernetes-cli
  - kubernetes-helm
  - kustomize
  - lame
  - ldns
  - leptonica
  - less
  - libarchive
  - libass
  - libassuan
  - libb2
  - libbluray
  - libcaca
  - libcbor
  - libcroco
  - libde265
  - libepoxy
  - libev
  - libevent
  - libffi
  - libfido2
  - libgcrypt
  - libgpg-error
  - libgphoto2
  - libheif
  - libice
  - libicns
  - libiconv
  - libidn
  - libidn2
  - libiscsi
  - libksba
  - liblqr
  - libmetalink
  - libmpc
  - libnghttp2
  - libogg
  - libomp
  - libpcap
  - libpng
  - libpq
  - libproxy
  - libpsl
  - libpthread-stubs
  - librdkafka
  - librist
  - librsvg
  - libsamplerate
  - libserdes
  - libsigc++
  - libsigc++@2
  - libsigsegv
  - libslirp
  - libsm
  - libsndfile
  - libsodium
  - libsoup
  - libsoxr
  - libssh
  - libssh2
  - libtasn1
  - libtiff
  - libtool
  - libunistring
  - libusb
  - libusb-compat
  - libuv
  - libvidstab
  - libvirt
  - libvmaf
  - libvo-aacenc
  - libvorbis
  - libvpx
  - libvterm
  - libx11
  - libxau
  - libxaw
  - libxcb
  - libxdmcp
  - libxext
  - libxft
  - libxinerama
  - libxml2
  - libxmu
  - libxpm
  - libxrender
  - libxt
  - libyaml
  - libzip
  - little-cms
  - little-cms2
  - llvm
  - lua
  - lynx
  - lz4
  - lzip
  - lzlib
  - lzo
  - m4
  - mackup
  - macos-term-size
  - make
  - makedepend
  - makensis
  - markdown
  - mas
  - maven
  - mbedtls
  - mcrypt
  - md4c
  - mhash
  - midnight-commander
  - minikube
  - moon-buggy
  - moreutils
  - mpdecimal
  - mpfr
  - mr
  - msmtp
  - mu
  - mysql
  - mysql-client
  - n
  - nano
  - ncurses
  - net-snmp
  - netcat
  - netpbm
  - nettle
  - nghttp2
  - nginx
  - nmap
  - node
  - node-build
  - nodenv
  - npth
  - nspr
  - nss
  - ocaml
  - ocamlbuild
  - octant
  - offlineimap
  - oniguruma
  - opam
  - opencore-amr
  - openexr
  - openjdk
  - openjdk@11
  - openjpeg
  - openldap
  - opensc
  - openshift-cli
  - openssh
  - openssl
  - opus
  - orc
  - otfcc-mac64
  - p11-kit
  - p7zip
  - packer
  - pandoc
  - pango
  - pangomm
  - pangomm@2.42
  - pangomm@2.46
  - pcre
  - pcre2
  - perl
  - pgcli
  # - php
  - pinentry
  - pipenv
  - pipx
  - pixman
  - pkg-config
  - pmd
  - pngpaste
  - popt
  - postgresql
  - potrace
  - protobuf
  - pth
  - pv
  - pyenv
  - pyenv-virtualenv
  - python-markdown
  - python-tabulate
  - python@3.10
  - qemu
  - qt
  - qt@5
  - rav1e
  - rbenv
  - re2c
  - readline
  - reaver
  - redis
  - relay
  - ripgrep
  - rlwrap
  - rsocket-cli
  - rtmpdump
  - rubberband
  - ruby
  - ruby-build
  - s-lang
  - sane-backends
  - sbcl
  - sbt
  - scala
  - schroedinger
  - scons
  - screen
  - sdl2
  - selenium-server
  - selenium-server-standalone
  - sfnt2woff
  - shared-mime-info
  - shellcheck
  - six
  - sl
  - snappy
  - socat
  - source-highlight
  - speex
  - sphinx-doc
  - springboot
  - sqlite
  - squashfs
  - srt
  - ssh-copy-id
  - stern
  - swagger-codegen
  - swi-prolog
  - swig
  - syncthing
  - tcl-tk
  - telnet
  - terminal-notifier
  - terraform
  - terraformer
  - tesseract
  - testdisk
  - texi2html
  - texinfo
  - the_silver_searcher
  - theora
  - tidy-html5
  - tmux
  - toilet
  - tokyo-cabinet
  - torsocks
  - trash
  - tree
  - ttfautohint
  - twine-pypi
  - unbound
  - unixodbc
  - unzip
  - utf8proc
  - vala
  - vault
  - vcsh
  - vde
  - watch
  - watchman
  - wdiff
  - webp
  - wemux
  - wget
  - winetricks
  - woff2
  - wrk
  - x264
  - x265
  - xapian
  - xhyve
  - xmlstarlet
  - xmlto
  - xorgproto
  - xpdf
  - xterm
  - xvid
  - xz
  - yajl
  - yamllint
  - yarn
  - yasm
  - youtube-dl
  - zenity
  - zeromq
  - zimg
  - zlib
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-history-substring-search
  - zstd

  - anaconda
  - android-file-transfer
  - atom
  - beyond-compare
  - chromedriver
  - dbeaver-community
  - double-commander
  - dropbox
  - firefox
  - font-alegreya
  - font-hack-nerd-font
  - font-iosevka
  - font-iosevka-slab
  - gimp
  - godot
  - google-chrome
  - handbrake
  - inkscape
  - istat-menus
  - iterm2
  - java
  - keycastr
  - lastpass
  - licecap
  - macdown
  - macfuse
  - mactex
  - minishift-beta
  - moom
  - nvm
  - osxfuse
  - pgadmin4
  - phpstorm
  - platypus
  - quicksilver
  - sequel-ace
  - sequel-pro
  - skitch
  - slack
  - slate
  - sonic-pi
  - spectacle
  - spotify
  - squirrel
  - sublime-text
  - texmaker
  - textmate
  - thunderbird
  - transmit
  - vagrant
  - vagrant-manager
  - veracrypt
  - virtualbox
  - visual-studio-code
  - vnc-viewer
  - webstorm
  - wkhtmltopdf
  - xquartz

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - adoptopenjdk
  # - anaconda
  # - android-file-transfer
  # - atom
  - beyond-compare
  - chromedriver
  # - dbeaver-community
  # - double-commander
  # - dropbox
  - firefox
  - font-alegreya
  - font-hack-nerd-font
  - font-iosevka
  - font-iosevka-slab
  # - gimp
  - godot
  - google-chrome
  # - handbrake
  # - inkscape
  - istat-menus
  - iterm2
  # - java
  # - keycastr
  - lastpass
  - licecap
  - macdown
  - macfuse
  - mactex
  - minishift-beta
  - moom
  - osxfuse
  - pgadmin4
  # - phpstorm
  - platypus
  - quicksilver
  - sequel-ace
  - sequel-pro
  - skitch
  - slack
  - slate
  - sonic-pi
  - spectacle
  - spotify
  - squirrel
  # - sublime-text
  - texmaker
  # - textmate
  # - thunderbird
  # - transmit
  - vagrant
  - vagrant-manager
  # - veracrypt
  - virtualbox
  - visual-studio-code
  - vnc-viewer

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
