---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_vscode: true
configure_vagrant: true
configure_asdf: true
configure_docker: true
configure_intellij: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
dockitems_persist: []

configure_sudoers: false
sudoers_custom_config: ''

homebrew_installed_packages:
  - curl
  - jenv # jEnv is a command line tool to help you forget how to set the JAVA_HOME environment variable. https://www.jenv.be/
  - dos2unix
  - git
  - the_silver_searcher
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-history-substring-search
  - zstd
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts #Used by iosevka fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - beyond-compare
  - chromedriver
  - font-alegreya
  - font-hack-nerd-font
  - font-iosevka
  - font-iosevka-slab
#  - google-chrome
  - iterm2
  - vnc-viewer

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
gem_packages: []
npm_packages: []
pip_packages: []

# Set to 'true' to configure Sublime Text.
configure_sublime: false

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Configure shell rc files
asdf_init_shell: false

#
asdf_version: "v0.9.0"

asdf_apt_global_dependencies: ["unzip", "git", "curl", "autoconf", "automake", "gcc",
"g++", "make", "patch", "pkg-config", "binutils", "libtool", "bison", "libreadline-dev", "automake", "autoconf", "build-essential", "libreadline-dev", "libncurses-dev", "libssl-dev", "libyaml-dev", "libxslt-dev", "libffi-dev", "libtool", "unzip", "git", "curl", "pkg-config", "libpcre3-dev", "zlib1g", "zlib1g-dev", "liblzma-dev"]

asdf_plugins:
    #- name: .net core
    #- name: 1password-cli
    #- name: act
    #- name: adr-tools
    - name: ag
      versions: ["2.2.0"]
      global: "2.2.0"
    #	- name: age
    #	- name: aks-engine
    #	- name: allure
    #	- name: alp
    #	- name: apache jmeter
    #	- name: argo-rollouts
    #	- name: aria2
    - name: asciidoctorj
      versions: ["2.5.3"]
      global: "2.5.3"
    #	- name: aws-copilot
    - name: aws-iam-authenticator
      versions: ["0.5.3"]
      global: "0.5.3"
    #	- name: aws-nuke
    - name: awscli
      versions: ["2.4.9"]
      global: "2.4.9"
    #	- name: babashka
    #	- name: bashbot	mathew
    #	- name: bat
    #	- name: batect
    #	- name: bats
    #	- name: bazel
    #	- name: binnacle
    #	- name: bitwarden
    #	- name: bombardier
    #	- name: bosh
    #	- name: boundary
    #	- name: brig
    #	- name: btrace
    #	- name: buf
    #	- name: buildpack
    - name: bundler
      versions: ["2.3.5"]
      global: "2.3.5"
    #	- name: caddy
    #	- name: carthage
    #	- name: ccache
    # - name: cf
    #   versions: ["8.1.0"]
    #   global: "8.1.0"
    #	- name: cfssl
    #	- name: chamber
    #	- name: cheat
    #	- name: chezscheme
    #	- name: chicken
    #	- name: clojure
    #	- name: cloudflared
    #	- name: cloudsql-proxy
    #	- name: clusterctl
    #	- name: cmake
    #	- name: cockroachdb
    #	- name: codefresh
    #	- name: concourse
    #	- name: conduit
    #	- name: conform
    #	- name: conftest
    #	- name: consul
    #	- name: container-diff
    #	- name: cookiecutter
    #	- name: copper
    #	- name: coq
    #	- name: crc
    #	- name: credhub
    - name: crossplane-cli
      versions: ["1.6.1"]
      repository: https://github.com/joke/asdf-crossplance-cli.git
      global: "1.6.1"
    #	- name: ctlptl
    #	- name: crystal
    #	- name: ctop
    #	- name: cue
    #	- name: d
    #	- name: dart
    #	- name: dasel
    #	- name: dbmate
    #	- name: delta
    # - name: deno
    #   versions: ["1.9.2"]
    #   global: "1.9.2"
    #	- name: dep
    #	- name: desk
    #	- name: devspace
    #	- name: dhall
    #	- name: digdag
    - name: direnv
      versions: ["2.9.0"]
      global: "2.9.0"
    #	- name: dive
    #	- name: djinni
    #	- name: docker-slim
    #	- name: docker-compose-v1
    #	- name: doctl
    #	- name: dome
    #	- name: dotenv-linter
    #	- name: dotty
    #	- name: draft
    #	- name: driftctl
    #	- name: duf
    #	- name: dust
    #	- name: dyff
    #	- name: editorconfig-checker
    # - name: eksctl
    #   versions: ["0.81.0-rc.0"]
    #   global: "0.81.0-rc.0"
    #	- name: elasticsearch
    #	- name: elixir
    # - name: elm
    #   versions: ["0.19.1"]
    #   global: "0.19.1"
    #	- name: embulk
    #	- name: emscripten
    #	- name: ephemeral
    #	- name: erlang
    #	- name: esy
    #    - name: etcd
    #  versions: ["latest"]
    #  global: "latest"
    #	- name: exa
    #	- name: fd
    #	- name: figma-export
    #	- name: firebase
    #	- name: flutter
    #	- name: flux2
    #	- name: fluxctl
    #	- name: fly
    - name: fzf
      versions: ["0.29.0"]
      global: "0.29.0"
    #	- name: gauche
    #	- name: gcloud
    #	- name: getenvoy
    #	- name: ghidra
    #	- name: ghq
    #	- name: ginkgo
    - name: git-chglog
      versions: ["0.9.1"]
      global: "0.9.1"
    - name: github-cli
      versions: ["2.4.0"]
      global: "2.4.0"
    - name: github-markdown-toc
      versions: ["1.2.0"]
      global: "1.2.0"
    #	- name: gitui
    #	- name: gleam
    #	- name: gnu guile
    #	- name: gnu nano
    - name: golang
      versions: ["1.9rc2"]
      global: "1.9rc2"
    - name: go-sdk
      versions: ["latest"]
      global: "latest"
    # - name: go-containerregistry
    #   versions: ["0.8.0"]
    #   global: "0.8.0"
    - name: jq
      versions: ["1.6"]
      global: "1.6"
    #   - name: go-jsonnet
    #     versions: ["latest"]
    #     global: "latest"
    #	- name: go-jira
    #	- name: gohugo
    #	- name: gojq
    #	- name: golangci-lint
    #	- name: go migrate
    #	- name: gomplate
    #	- name: gopass
    #	- name: goreleaser
    #	- name: goss
    - name: graalvm
      versions: ["latest"]
      global: "latest"
    - name: gradle
      versions: ["7.4-rc-1"]
      global: "7.4-rc-1"
    #	- name: gradle profiler
    #	- name: grails
    #	- name: grain
    - name: groovy
      versions: ["4.0.0-rc-2"]
      global: "4.0.0-rc-2"
    #	- name: grpcurl	asdf
    #	- name: grpc-health-probe
    #	- name: grype
    #	- name: gwvault
    #	- name: hadolint
    #	- name: hamler
    #	- name: haskell
    #	- name: hasura-cli
    #	- name: haxe
    - name: helm
      versions: ["3.8.0-rc.2"]
      global: "3.8.0-rc.2"
    #	- name: helm chart releaser
    #	- name: helm chart tester
    #	- name: helm diff
    #	- name: helm-docs
    #	- name: helmfile
    #	- name: hey
    - name: httpie-go
      versions: ["0.7.0"]
      global: "0.7.0"
    #	- name: hub
    #	- name: hugo
    #	- name: hygen
    #	- name: idris
    #	- name: idris2
    #	- name: imagemagick
    #	- name: imgpkg
    #	- name: inlets
    #	- name: io
    # - name: istioctl
    #   versions: ["1.9.9"]
    #   global: "1.9.9"
    - name: java
      versions: ["corretto-8.322.06.1", "corretto-11.0.14.9.1", "corretto-17.0.2.8.1"]
      global: "corretto-8.322.06.1"
    #	- name: jb
    #	- name: jbang
    #	- name: jmespath
    #	- name: jreleaser
    #	- name: json2k8s
    #	- name: jsonnet
    #	- name: julia
    #	- name: just
    #	- name: jx
    #	- name: k3d
    #	- name: k3sup
    #	- name: k6
    #	- name: k9s
    #	- name: kapp
    #	- name: kbld
    #	- name: kconf
    # - name: kim
    #   repository: git@github.com:drgeb/asdf-kim.git
    #   versions: ["v0.1.0-beta.7"]
    #   global: "v0.1.0-beta.7"
    - name: kind
      versions: ["0.11.1"]
      global: "0.11.1"
    #	- name: ki
    #	- name: kn
    #	- name: ko
    #	- name: kompose
    #	- name: kops
    - name: kotlin
      versions: ["1.6.10"]
      global: "1.6.10"
    #	- name: kpt
    #	- name: kscript
    #	- name: krew
    #	- name: ksonnet
    #	- name: kube-capacity
    #	- name: kube-code-generator
    #	- name: kube-controller-tools
    #	- name: kubebuilder
    - name: kubectl
      versions: ["1.9.9"]
      global: "1.9.9"
    #	- name: kubectl-bindrole
    #	- name: kubectx
    #	- name: kubefedctl
    #	- name: kubergrunt
    # - name: kubeseal  
    #   versions: ["0.17.2"]
    #   global: "0.17.2"
    #	- name: kubesec
    #	- name: kubespy
    #	- name: kubeval
    #	- name: kubie
    - name: kustomize
      versions: ["4.4.1"]
      global: "4.4.1"
    #	- name: kwt
    #	- name: lab
    #	- name: lazygit
    #	- name: lean
    #	- name: leiningen
    #	- name: levant
    #	- name: lfe
    #	- name: link (system tools)
    #	- name: linkerd
    #	- name: litestream
    #	- name: logtalk
    #	- name: loki-logcli
    #	- name: lua
    #	- name: luajit
    #	- name: make
    - name: maven
      versions: ["3.8.4"]
      global: "3.8.4"
    #	- name: meson
    #	- name: micronaut
    #	- name: mill
    #	- name: minikube
    #	- name: minio
    #	- name: minio client
    #	- name: minishift
    #	- name: mint
    #	- name: mitmproxy
    #	- name: mkcert
    #	- name: mlton
    #	- name: mockery
    #	- name: mongo-tools
    #- name: mongodb
    #  versions: ["latest"]
    #  global: "latest"
    #	- name: mongosh
    #	- name: mvnd
    #	- name: mysql
    #	- name: neko virtual machine
    #	- name: neovim
    #	- name: newrelic-cli
    #	- name: nim
    #	- name: ninja
    - name: nodejs
      versions: ["16.13.2"]
      global: "16.13.2"
    #	- name: nomad
    #	- name: nova
    #	- name: nuclei
    #	- name: oc
    #	- name: ocaml
    #	- name: om
    #	- name: opa
    #	- name: opam
    #	- name: openresty
    #	- name: operator sdk
    #	- name: osm
    #	- name: pachctl
    - name: packer
      versions: ["1.7.9"]
      global: "1.7.9"
    #	- name: peco
    #	- name: perl
    #	- name: php
    #	- name: pivnet
    #	- name: please
    #	- name: pluto
    #	- name: pnpm
    #	- name: poetry
    #	- name: polaris
    #	- name: popeye
    #	- name: postgres
    #	- name: pre-commit
    #	- name: protoc
    #	- name: psc-package
    #	- name: pulumi
    # TODO for purescript missing purs
    # - name: purescript
    #   versions: ["0.9.3"]
    #   global: "0.9.3"
    #	- name: purty
    #	- name: python
    #	- name: r
    #	- name: rabbitmq
    #	- name: racket
    #	- name: rancher
    #	- name: rbac-lookup
    #	- name: rclone
    #	- name: rebar
    - name: redis
      versions: ["6.2.6"]
      global: "6.2.6"
    - name: redis-cli
      versions: ["6.2.6"]
      global: "6.2.6"
    #	- name: redskyctl
    #	- name: reg
    #	- name: richgo
    #	- name: riff
    #	- name: ripgrep
    #	- name: rke
    #	- name: rlwrap
    - name: ruby
      versions: ["3.1.0"]
      global: "3.1.0"
    #	- name: rust
    - name: saml2aws
    #	- name: sbt
    #	- name: scala
    #	- name: scaleway-cli
    #	- name: scenery
    #	- name: semgrep
    #	- name: sentinel
    #	- name: serf
    #	- name: shellcheck
    #	- name: shellspec
    #	- name: shfmt
    #	- name: sinker
    #	- name: skaffold
    #	- name: snyk
    #	- name: solidity
    #	- name: sops
    #	- name: sopstool
    #	- name: sourcery
    #	- name: spago
    #	- name: spin
    - name: spring-boot
      versions: ["2.6.3"]
      global: "2.6.3"
    #	- name: spruce
    #	- name: sqlite
    #	- name: stack
    #	- name: starboard
    #	- name: starship
    #	- name: steel bank common lisp (sbcl)
    #	- name: stern
    #	- name: swiftformat
    #	- name: swiftgen
    #	- name: swiftlint
    #	- name: swiprolog
    #	- name: syncher
    #	- name: talos
    #	- name: tanka
    #	- name: task
    #	- name: tekton-cli
    - name: terraform
      versions: ["1.1.4"]
      global: "1.1.4"
    #	- name: terraform-docs
    - name: terraform-ls
      versions: ["0.25.2"]
      global: "0.25.2"
    #	- name: terraform-lsp
    - name: terraform-validator
      versions: ["3.1.3"]
      global: "3.1.3"
    #	- name: terragrunt
    #	- name: tflint
    #	- name: tfsec
    #	- name: tfupdate
    #	- name: tilt
    - name: tmux
      versions: ["3.3-rc"]
      global: "3.3-rc"
    #	- name: trdsql
    #	- name: tridentctl
    #	- name: trivy
    #	- name: upx
    #	- name: v
    #	- name: vals
    #	- name: vault
    #	- name: velero
    #	- name: vendir
    #	- name: vcluster
    - name: vim
      versions: ["8.2.4219"]
      global: "8.2.4219"
    #	- name: watchexec
    #	- name: wasi sdk
    - name: waypoint
      versions: ["0.7.1"]
      global: "0.7.1"
    #	- name: websocat
    #	- name: wren cli
    #	- name: wtfutil
    #	- name: xcodegen
    #	- name: xh
    #	- name: yadm
    - name: yarn
      versions: ["1.22.17"]
      global: "1.22.17"
    - name: yq
      versions: ["4.9.8"]
      global: "4.9.8"
    #	- name: ytt
    #	- name: zephyr
    #	- name: zig
    #	- name: zola
    #	- name: zoxide
    #
# IntelliJ
# IntelliJ IDEA version number
intellij_version: '2021.3.1'

# Mirror where to dowload IntelliJ IDEA redistributable package from
# Using HTTP because of https://github.com/ansible/ansible/issues/11579
intellij_mirror: 'http://download.jetbrains.com/idea'

# Edition to install (community or ultimate)
intellij_edition: community

# Set to 'false' so it skips the installation of Intellij IDEA in case it is
# already installed (even if a different version than requested)
intellij_force: true

# Base installation directory for any IntelliJ IDEA distribution
intellij_install_dir: /opt/idea/idea-{{ intellij_edition }}-{{ intellij_version }}

# Location of the default Apache Maven installation for IntelliJ IDEA projects
# Defaults to value of ansible_local.maven.general.home (see gantsign.maven role)
intellij_default_maven_home: '{{ ((((ansible_local | default(dict())).maven | default(dict())).general | default(dict())).home | default(None)) }}'

# URL for IntelliJ IDEA plugin manager web service
intellij_plugin_manager_url: 'https://plugins.jetbrains.com/pluginManager/'

# List of users to configure IntelliJ IDEA for
users:
  - username: 'gerry.bennett' # Unix user name
    intellij_group: 'staff'   # Unix group for the user's files/directories (optional - defaults to username)
    intellij_jdks:
      - name: 'corretto-11.0.14.9.1' # The name use want to use for this JDK
        home: '.asdf/installs/java/corretto-11.0.14.9.1' 
        # The path to the JDK home.
    # The name of the JDK you want to be the default for new projects.
    # Required if you specify `intellij_jdks`.
    # Must match the name given to one of the `intellij_jdks`.
    intellij_default_jdk: 'corretto-11.0.14.9.1'
    intellij_disabled_plugins: # see ~/.*Idea*/config/disabled_plugins.txt
      - # Plugin ID
    intellij_codestyles:
      - name: # Name (must match the value in the XML file /code_scheme/@name)
        url: # URL to download the codestyles XML from
    intellij_default_codestyle: # Name (must match the value in the XML file /code_scheme/@name)
    intellij_inspection_profiles:
      - name: # Name (must match the value in the XML file /profile/option[@name='myName']/@value)
        url: # URL to download the inspection profile XML from
    intellij_default_inspection_profile: # Name (must match the value in the XML file /profile/option[@name='myName']/@value)
    intellij_plugins:
      - # Plugin ID of plugin to install
    # Ultimate Edition only: location of the IntelliJ license key on the Ansible master.
    # Your license key can be found at ~/.IntelliJIdea2017.1/config/idea.key
    intellij_license_key_path: # e.g. '/vagrant/idea.key'

# Directory to store files downloaded for IntelliJ IDEA installation
intellij_download_dir: "{{ x_ansible_download_dir | default(ansible_env.HOME + '/.ansible/tmp/downloads') }}"

# Timeout for IntelliJ IDEA download response in seconds
intellij_idea_download_timeout_seconds: 600
