---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: tkimball83.iterm2
      iterm2_defaults:
        - name: PrefsCustomFolder
          type: string
          value: 
        - name: LoadPrefsFromCustomFolder
          type: bool
          value: true
        # - name: OnlyWhenMoreTabs
        #   type: string
        #   value: 0
        # - name: PromptOnQuit
        #   type: bool
        #   value: false
      when: configure_iterm2
      tags: ['config_iterm2']
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: kb9zzw.garage.vscode 
      when: configure_vscode
      tags: ['vscode']
    - role: kb9zzw.garage.vagrant
      when: configure_vagrant
      tags: ['vagrant']
    - role: markosamuli.asdf
      when: configure_asdf
      tags: ['asdf']
    - role: kb9zzw.garage.docker
      when: configure_docker
      tags: ['docker']
    - role: fernandrone.intellij
      when: configure_intellij
      tags: ['intellij']
    - role: drgeb.tilt
      when: configure_tilt   
      tags: ['tilt']
    - role: drgeb.myclone
      when: configure_myclone    
      tags: ['myclone']
    - role: drgeb.config_dotfilemanagement
      when: configure_dotfilemanagement
      tags: ['config_dotfilemanagement']
    - role: drgeb.ohmyzsh
      when: configure_ohmyzsh    
      tags: ['ohmyzsh']
    - role: drgeb.gpg
      tags: ['gpg']

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']


    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
