---
    - name: Ensure Sublime Text directories exist.
      ansible.builtin.file:
          path: '{{ sublime_textdir_item }}'
          state: directory
          mode: 0644
      loop:
          - '{{ sublime_base_path }}/{{ sublime_config_path }}'
          - '{{ sublime_base_path }}/Installed Packages'
      loop_control:
          loop_var: sublime_textdir_item

    - name: Ensure Sublime Package Control is installed.
      ansible.builtin.get_url:
          url: https://packagecontrol.io/Package%20Control.sublime-package
          dest: '{{ sublime_base_path }}/Installed Packages/Package Control.sublime-package'
          mode: 0644

    - name: Ensure Sublime Package Control Packages are configured.
      ansible.builtin.template:
          src: templates/Package_Control.sublime-settings.j2
          dest: '{{ sublime_base_path }}/{{ sublime_config_path }}/Package Control.sublime-settings'
          mode: 0644

    - name: Ensure Sublime text user Preferences and theme are set.
      ansible.builtin.copy:
          src: files/sublime/{{ item }}
          dest: '{{ sublime_base_path }}/{{ sublime_config_path }}/{{ item }}'
          mode: 0644
      loop:
          - Cobalt (SL).tmTheme
          - Markdown.sublime-settings
          - Plain text.sublime-settings
          - Preferences.sublime-settings
          - WordCount.sublime-settings
      loop_control:
          loop_var: sb_item
