---
# tasks file for gpg
- name: include tasks
  include_tasks: "{{ lookup('first_found', possible) }}"
  vars:
    possible:
      - "{{ platform }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}-{{ ansible_architecture }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}-{{ ansible_architecture }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}-{{ ansible_architecture }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "{{ ansible_system }}-{{ ansible_architecture }}.yml"
      - "{{ ansible_system }}.yml"
      - all.yml
      - unsupported.yml

