#!/usr/bin/env sh

############################################################
# Attempt to set APP_HOME
# Resolve links:  may be a link
PRG="$0"
# Need this for relative symlinks.
while [ -h "PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> .*$'`
    if expr "$link" : /.* > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
SAVED="`pwd`"
cd "`dirname "$PRG"`/.." >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="mac-dev-playbook"
APP_BASE_NAME=`basename "$0"`

############################################################

PLAYBOOK=${1:-main}
ENVIRONMENT=${ENVIRONMENT:-dev}
LOG_DIR=${LOG_DIR:-~/logs}
LOG_FILE=${LOG_FILE:-driver-server.log}
OPTIONS=${OPTIONS:-}
DATE=$(date '+%Y%m%d%H%M%S')

if [ ! -z ${LOG_DIR} ]; then
    mkdir -pv ${LOG_DIR}
fi
LOG_FILE=${LOG_DIR}/driver-windows.log

if [ ! -z SILENT ]; then
    ansible-playbook  -i inventory playbooks/${PLAYBOOK}.yml ${OPTIONS} | tee ${LOG_FILE}
else
    ansible-playbook  -i inventory playbooks/${PLAYBOOK}.yml ${OPTIONS} -vvvv | tee ${LOG_FILE}
fi
