---
- name: Aid ASDF management
  hosts: all
  vars_files:
    - "{{ playbook_dir }}/vars/tool-versions.yml"
  roles:
  - role: elliotweiser.osx-command-line-tools
  - role: geerlingguy.mac.homebrew
  - role: osx_provisioner.asdf
    asdf_plugins:
    #   environment:
    #     KERL_CONFIGURE_OPTIONS: "--without-javac --with-ssl=/usr/local/opt/openssl@1.1 --disable-hipe"
    #     CFLAGS: "-O2 -g -fno-stack-check"
    # - name: "python"
    #   versions: "3.9.1"
      - name: "java"
        versions: ["{{ java }}"]
        global: "{{ java }}"
      - name: "ag"
        versions: ["{{ ag }}"]
        global: "{{ ag }}"
      - name: "argocd"
        versions: ["{{ argocd }}"]
        global: "{{ argocd }}"
      - name: "asciidoctorj"
        versions: ["{{ asciidoctorj }}"]
        global: "{{ asciidoctorj }}"
      - name: "aws-iam-authenticator"
        versions: ["{{ aws_iam_authenticator }}"]
        global: "{{ aws_iam_authenticator }}"
      - name: "awscli"
        versions: ["{{ awscli }}"]
        global: "{{ awscli }}"
      - name: "bats"
        versions: ["{{ bats }}"]
        global: "{{ bats }}"
      - name: "bundler"
        versions: ["{{ bundler }}"]
        global: "{{ bundler }}"
      - name: "circleci-cli"
        versions: ["{{ circleci_cli }}"]
        global: "{{ circleci_cli }}"
      - name: "coursier"
        versions: ["{{ coursier }}"]
        global: "{{ coursier }}"
      - name: "crossplane-cli"
        versions: ["{{ crossplane_cli }}"]
        global: "{{ crossplane_cli }}"
      - name: "direnv"
        versions: ["{{ direnv }}"]
        global: "{{ direnv }}"
      - name: "dive"
        versions: ["{{ dive }}"]
        global: "{{ dive }}"
      - name: "docker-compose-v1"
        versions: ["{{ docker_compose_v1 }}"]
        global: "{{ docker_compose_v1 }}"
      - name: "fzf"
        versions: ["{{ fzf }}"]
        global:  "{{ fzf }}"
      - name: "git-chglog"
        versions: ["{{ git_chglog }}"]
        global: "{{ git_chglog }}"
      - name: "github-cli"
        versions: ["{{ github_cli }}"]
        global: "{{ github_cli }}"
      - name: "github-markdown-toc"
        versions: ["{{ github_markdown_toc }}"]
        global: "{{ github_markdown_toc }}"
      - name: "golang"
        versions: ["{{ golang }}"]
        global: "{{ golang }}"
      - name: "graalvm"
        versions: ["{{ graalvm }}"]
        global: "{{ graalvm }}"
      - name: "jq"
        versions: ["{{ jq }}"]
        global: "{{ jq }}"
      - name: "gradle"
        versions: ["{{ gradle }}"]
        global: "{{ gradle }}"
      - name: "groovy"
        versions: ["{{ groovy }}"]
        global: "{{ groovy }}"
      - name: "helm"
        versions: ["{{ helm }}"]
        global: "{{ helm }}"
      - name: "httpie-go"
        versions: ["{{ httpie_go }}"]
        global: "{{ httpie_go }}"
      - name: "kind"
        versions: ["{{ kind }}"]
        global: "{{ kind }}"
      - name: "kotlin"
        versions: ["{{ kotlin }}"]
        global: "{{ kotlin }}"
      - name: "kubectl"
        versions: ["{{ kubectl }}"]
        global: "{{ kubectl }}"
      - name: "kustomize"
        versions: ["{{ kustomize }}"]
        global: "{{ kustomize }}"
      - name: "maven"
        versions: ["{{ maven }}"]
        global: "{{ maven }}"
      - name: "nodejs"
        versions: ["{{ nodejs }}"]
        global: "{{ nodejs }}"
      - name: "packer"
        versions: ["{{ packer }}"]
        global: "{{ packer }}"
      - name: "redis"
        versions: ["{{ redis }}"]
        global: "{{ redis }}"
      - name: "redis-cli"
        versions: ["{{ redis_cli }}"]
        global: "{{ redis_cli }}"
      - name: "ripgrep"
        versions: ["{{ ripgrep }}"]
        global: "{{ ripgrep }}"
      - name: "rust"
        versions: ["{{ rust }}"]
        global: "{{ rust }}"
      - name: "ruby"
        versions: ["{{ ruby }}"]
        global: "{{ ruby }}"
      - name: "saml2aws"
        versions: ["{{ saml2aws }}"]
        global: "{{ saml2aws }}"
      - name: "shfmt"
        versions: ["{{ shfmt }}"]
        global: "{{ shfmt }}"
      - name: "spring-boot"
        versions: ["{{ spring_boot }}"]
        global: "{{ spring_boot }}"
      - name: "terraform"
        versions: ["{{ terraform }}"]
        global: "{{ terraform }}"
      - name: "terraform-ls"
        versions: ["{{ terraform_ls }}"]
        global: "{{ terraform_ls }}"
      - name: "terraform-validator"
        versions: ["{{ terraform_validator }}"]
        global: "{{ terraform_validator }}"
      - name: "tmux"
        versions: ["{{ tmux }}"]
        global: "{{ tmux }}"
      - name: "vim"
        versions: ["{{ vim }}"]
        global: "{{ vim }}"
      - name: "waypoint"
        versions: ["{{ waypoint }}"]
        global: "{{ waypoint }}"
      - name: "yarn"
        versions: ["{{ yarn }}"]
        global: "{{ yarn }}"
      - name: "yj"
        versions: ["{{ yj }}"]
        global: "{{ yj }}"
      - name: "yq"
        versions: ["{{ yq }}"]
        global: "{{ yq }}"
      - name: "tilt"
        versions: ["{{ tilt }}"]
        global: "{{ tilt }}"
      - name: "python"
        versions: ["{{ python }}"]
        global: "{{ python }}"
      - name: "asdf-postgres"
        versions: ["{{ asdf_postgres }}"]
        global: "{{ asdf_postgres }}"
      - name: "liquibase"
        versions: ["{{ liquibase }}"]
        global: "{{ liquibase }}"
      - name: "jmeter"
        versions: ["{{ jmeter }}"]
        global: "{{ jmeter }}"
      - name: "lua"
        versions: ["{{ lua }}"]
        global: "{{ lua }}"
      - name: "pulumi"
        versions: ["{{ pulumi }}"]
        global:  "{{ pulumi }}"
      - name: "poetry"
        versions: ["{{ poetry }}"]
        global: "{{ poetry }}"
      - name: "jbang"
        versions: ["{{ jbang }}"]
        global: "{{ jbang }}"
      - name: "shellcheck"
        versions: ["{{ shellcheck }}"]
        global: "{{ shellcheck }}"
      - name: "pgbadger"
        versions: ["{{ pgbadger }}"]
        global: "{{ pgbadger }}"
      - name: "gopass"
        versions: ["{{ gopass }}"]
        global: "{{ gopass }}"
      - name: shfmt
        versions: ["{{ shfmt }}"]
        global: "{{ shfmt }}"
