---
- name: doom
  hosts: mac

  collections:
    - drgeb.development

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: [always]

  tasks:
    - import_role:
        name: drgeb.development.emacs_doom
      tags: [emacs_doom]
      when: configure_emacs_doom
