---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: configure_homebrew
    - role: elliotweiser.osx-command-line-tools
      when: configure_osx
      tags: ['osx']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: drgeb.vscode 
      when: configure_vscode
      tags: ['vscode']
    - role: kb9zzw.garage.vagrant
      when: configure_vagrant
      tags: ['vagrant']
    - role: markosamuli.asdf
      when: configure_asdf
      tags: ['asdf']
    - role: kb9zzw.garage.docker
      when: configure_docker
      tags: ['docker']
    - role: fernandrone.intellij
      when: configure_intellij
      tags: ['intellij']
    - role: drgeb.teamcity
      when: configure_teamcity
      tags: ['teamcity']
    - role: drgeb.tilt
      when: configure_tilt   
      tags: ['tilt']
    - role: drgeb.myclone
      when: configure_myclone    
      tags: ['myclone']
    - role: drgeb.config_dotfilemanagement
      when: configure_dotfilemanagement
      tags: ['dotfiles']
    - role: drgeb.ohmyzsh
      when: configure_ohmyzsh    
      tags: ['ohmyzsh']
    - role: drgeb.gpg
      tags: ['gpg']
    - role: drgeb.outlook
      when: configure_outlook
      tags: ['outlook']
    - role: drgeb.iterm2
      when: configure_iterm2
      tags: ['iterm2']
  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/sublime-text.yml
      when: configure_sublime
      tags: ['sublime-text']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']

    - name: Ensure wallpapers repo is available
      ansible.builtin.git:
        repo: git@github.com:makccr/wallpapers.git
        dest: "{{ workspace_dir }}/git/github.com/makccr/wallpapers"

    - name: Ensure a symbolic link in Pictures to wallpapers
      ansible.builtin.file:
        src: "{{ workspace_dir }}/git/github.com/makccr/wallpapers"
        dest: "{{ ansible_env.HOME }}/Pictures/wallpapers-mackccr"
        state: link

    - name: Ensure wallpapers-ii repo is available
      ansible.builtin.git:
        repo: git@github.com:makccr/wallpapers-ii.git
        dest: "{{ workspace_dir }}/git/github.com/makccr/wallpapers-ii"

    - name: Ensure a symbolic link in Pictures to wallpapers
      ansible.builtin.file:
        src: "{{ workspace_dir }}/git/github.com/makccr/wallpapers-ii"
        dest: "{{ ansible_env.HOME }}/Pictures/wallpapers-ii-mackccr"
        state: link
