---
- hosts: mac

  collections:
    - drgeb.development

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: [always]

  tasks:
    - ansible.builtin.import_role:
        name: drgeb.development.spacemacs
      tags: [spacemacs]
      when: configure_spacemacs
