---
- hosts: mac

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: drgeb.spacemacs
      tags: ['spacemacs']
      when: configure_spacemacs
